
# ### GEnerate Claim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-demo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard
---
## create container and mount points
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-west2-docker.pkg.dev/cscicloudcomputing/docker-registry/container2:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: my-volume
              mountPath: /Tapan_PV_dir
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc-demo
---
apiVersion: v1
kind: Service
metadata:
  name: container2endpoint
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8081